_wandb:
    value:
        cli_version: 0.19.3
        m: []
        python_version: 3.10.16
        t:
            "1":
                - 1
                - 41
                - 49
                - 55
                - 83
            "2":
                - 1
                - 41
                - 49
                - 55
                - 83
            "3":
                - 2
                - 14
                - 23
                - 55
                - 61
            "4": 3.10.16
            "5": 0.19.3
            "8":
                - 5
            "12": 0.19.3
            "13": linux-x86_64
actuator_config:
    value:
        actuator_network_dir: null
        future_len: null
        history_len: null
        prediction_len: null
camera_names:
    value:
        - top
ckpt_dir:
    value: trainings/yin_test_1
episode_len:
    value: 500
eval_every:
    value: 500
load_pretrain:
    value: false
lr:
    value: 1e-05
num_steps:
    value: 2000
onscreen_render:
    value: false
policy_class:
    value: ACT
policy_config:
    value:
        action_dim: 16
        backbone: resnet18
        camera_names:
            - top
        dec_layers: 7
        dim_feedforward: 3200
        enc_layers: 4
        hidden_dim: 512
        kl_weight: 1
        lr: 1e-05
        lr_backbone: 1e-05
        nheads: 8
        no_encoder: false
        num_queries: 10
        vq: false
        vq_class: null
        vq_dim: null
real_robot:
    value: true
resume_ckpt_path:
    value: null
save_every:
    value: 500
seed:
    value: 0
state_dim:
    value: 14
task_name:
    value: aloha_mobile_yin_xu_train
temporal_agg:
    value: false
validate_every:
    value: 500
